# Generated by Django 5.1 on 2024-12-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(blank=True, choices=[('private', 'private'), ('Government', 'Governmnet'), ('Sem-Gov', 'Sem-Gov')], max_length=100, null=True),
        ),
    ]
