# Generated by Django 5.1 on 2024-12-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='university',
            new_name='teachers',
        ),
    ]
