# Generated by Django 5.1 on 2024-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_rename_university_staff_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='staff_no',
            new_name='phone',
        ),
    ]
